os:
    - linux
    - osx
before_script:
    - wget https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz
    - ./tools/ruby_ship_build.sh ./ruby-2.3.1.tar.gz
script:
    - ./bin/ruby_ship.sh tools/implementation_tests.rb
